server:
  port: 3000

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/gitlab_commit_log?serverSelectionTimeoutMS=10000&connectTimeoutMS=10000&socketTimeoutMS=60000

github:
  base-url: https://api.github.com

gitlab:
  base-url: https://gitlab.com/api/v4

logging:
  file:
    name: logs/app.log
  level:
    com.example.gitlabcommitlog: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
